# Site settings
author: Christian Simon
title: My Journey
header-img: img/home-bg.png
email: csimon1127@gmail.com
copyright_name: Christian Simon
description: > # this means to ignore newlines until "baseurl:"
  Through the Experience of Software Development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Christian-Simon1127

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
